repos:
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0
  hooks:
  - id: yapf
- repo: local
  hooks:
  - id: isort
    stages: [commit,push]
    name: isort
    entry: pipenv run isort
    language: system
