name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Publish docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        repository: acaire/stax
        tag_with_ref: true
        push: false
        build_args: VERSION=${{ github.event.release.tag_name }}
